# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David Mataró i Ciller
tagline:          My Blog
url:              http://davidmataro.com
paginate:         10
baseurl:          /
author:
  name:           David Mataró i Ciller
  url:            http://davidmataro.com
  email:          jo@davidmataro.com

# Pages
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
#version:          1.0.0
#github:
#  repo:           https://github.com/poole/poole
