markdown: redcarpet
highlighter: null
permalink: /:title

url: http://www.davidmataro.com
baseurl: http://www.davidmataro.com

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
