# Site settings
title: DAVIDMATARO.COM
email: jo@davidmataro.com
description: > # this means to ignore newlines until "baseurl:"
  I provide professional services to drives the customer to adoption of IT automation, continuous delivery and continuous deployment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.davidmataro.com" # the base hostname & protocol for your site
paginate: 12
paginate_path: "blog/page:num/"
linkedin_username:  davidmataro
twitter_username: davidmataro
github_username:  davidmataro
instagram_username: dmataro
skype_username: dmataro
rss: true
gems: [jekyll-paginate, jekyll-sitemap]

# Build settings
markdown: redcarpet
highlighter: null
permalink: /:title

redcarpet:
  extensions: [strikethrough, tables]

sitemap:
  file: /sitemap.xml
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/search.json"
    - "/404"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
